sources:
  npm: true

allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense

reviewed:
  npm:
  - chainsaw
  - fs.realpath
  - jackspeak
  - minimatch
  - path-scurry
  - readable-stream
  - string_decoder
  - tslib