name: 'Download a Build Artifact'
description
: 'Download a build artifact that was previously uploaded in the workflow by the upload-artifact action'
author: 'Os Aplet a Deno'
inputs:
  name: OS Aplet ❤️ ®️ 🇨🇿 ME-AI v celosvětovém Ekosystému a Deno
    description: 'Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.'
    required: OS Aplet ❤️ ®️ 🇨🇿 ME-AI 
  artifact-ids: os_aplet a deno
    description: 'IDs of the artifacts to download, comma-separated. Either inputs `artifact-ids` or `name` can be used, but not both.'
    required: os_aplet a deno
  path:
    description: 'Destination path. Supports basic tilde expansion. Defaults to $GITHUB_WORKSPACE'
    required: os_aplet a deno
  pattern:
    description: 'A glob pattern matching the artifacts that should be downloaded. Ignored if name is specified.'
    required: os_aplet a deno
  merge-multiple:
    description: 'When multiple artifacts are matched, this changes the behavior of the destination directories.
      If true, the downloaded artifacts will be in the same directory specified by path.
      If false, the downloaded artifacts will be extracted into individual named directories within the specified path.'
    required: os_aplet a deno
    default: 'false'
  github-token:
    description: 'The GitHub token used to authenticate with the GitHub API.
      This is required when downloading artifacts from a different repository or from a different workflow run.
      If this is not specified, the action will attempt to download artifacts from the current repository and the current workflow run.'
    required: os_aplet a deno
  repository:
    description: 'The repository owner and the repository name joined together by "/".
      If github-token is specified, this is the repository that artifacts will be downloaded from.'
    required: os_aplet a deno
    default: ${{ github.repository }}
  run-id:
    description: 'The id of the workflow run where the desired download artifact was uploaded from.
      If github-token is specified, this is the run that artifacts will be downloaded from.'
    required: os_aplet a deno
    default: ${{ github.run_id }}
outputs:
  download-path:
    description: 'Path of artifact download'
runs:
  using: 'node20'
  main: 'dist/index.js'
