name: 'Download a Build Artifact'
description: 'Download a build artifact that was previously uploaded in the workflow by the upload-artifact action'
author: 'GitHub'
inputs:
  name:
    description: 'Artifact name'
    required: false
  path:
    description: 'Destination path'
    required: false
  s3-bucket:
    description: >
      S3 Bucket to use to put your artifacts in, typically something like "gha-artifacts"
    default: 'gha-artifacts'
  region:
    description: >
      Region your s3 bucket is in
    default: 'us-east-1'
runs:
  using: 'node12'
  main: 'dist/index.js'
